security:

    role_hierarchy:
        ROLE_SISTEMAS_CEF_SEGURO_TIPO:
        - ROLE_APP_ADMIN_SEGURO_TIPO_LIST
        - ROLE_APP_ADMIN_SEGURO_TIPO_VIEW
        - ROLE_APP_ADMIN_SEGURO_TIPO_CREATE
        - ROLE_APP_ADMIN_SEGURO_TIPO_EDIT
        - ROLE_APP_ADMIN_SEGURO_TIPO_DELETE
        ROLE_SISTEMAS_CEF_SEGURO_AMBITO:
        - ROLE_APP_ADMIN_SEGURO_AMBITO_LIST
        - ROLE_APP_ADMIN_SEGURO_AMBITO_VIEW
        - ROLE_APP_ADMIN_SEGURO_AMBITO_CREATE
        - ROLE_APP_ADMIN_SEGURO_AMBITO_EDIT
        - ROLE_APP_ADMIN_SEGURO_AMBITO_DELETE
        ROLE_SISTEMAS_CEF_SEGURO_TRANSPORTE:
        - ROLE_APP_ADMIN_SEGURO_TRANSPORTE_LIST
        - ROLE_APP_ADMIN_SEGURO_TRANSPORTE_VIEW
        - ROLE_APP_ADMIN_SEGURO_TRANSPORTE_CREATE
        - ROLE_APP_ADMIN_SEGURO_TRANSPORTE_EDIT
        - ROLE_APP_ADMIN_SEGURO_TRANSPORTE_DELETE
        ROLE_SISTEMAS_CEF_SEGURO_FRANQUICIA:
        - ROLE_APP_ADMIN_SEGURO_FRANQUICIA_LIST
        - ROLE_APP_ADMIN_SEGURO_FRANQUICIA_VIEW
        - ROLE_APP_ADMIN_SEGURO_FRANQUICIA_CREATE
        - ROLE_APP_ADMIN_SEGURO_FRANQUICIA_EDIT
        - ROLE_APP_ADMIN_SEGURO_FRANQUICIA_DELETE
        ROLE_SISTEMAS_CEF_SEGURO_TARIFA:
        - ROLE_APP_ADMIN_SEGURO_TARIFA_LIST
        - ROLE_APP_ADMIN_SEGURO_TARIFA_VIEW
        - ROLE_APP_ADMIN_SEGURO_TARIFA_CREATE
        - ROLE_APP_ADMIN_SEGURO_TARIFA_EDIT
        - ROLE_APP_ADMIN_SEGURO_TARIFA_DELETE
        ROLE_SISTEMAS_CEF_DOCUMENTACION:
        - ROLE_APP_ADMIN_DOCUMENTACION_LIST
        - ROLE_APP_ADMIN_DOCUMENTACION_VIEW
        - ROLE_APP_ADMIN_DOCUMENTACION_CREATE
        - ROLE_APP_ADMIN_DOCUMENTACION_EDIT
        - ROLE_APP_ADMIN_DOCUMENTACION_DELETE
        ROLE_SISTEMAS_CEF_TIPO_EMPRESA:
        - ROLE_APP_ADMIN_TIPO_EMPRESA_LIST
        - ROLE_APP_ADMIN_TIPO_EMPRESA_VIEW
        - ROLE_APP_ADMIN_TIPO_EMPRESA_CREATE
        - ROLE_APP_ADMIN_TIPO_EMPRESA_EDIT
        - ROLE_APP_ADMIN_TIPO_EMPRESA_DELETE
        ROLE_ADMIN_PUBLI_CCF:
        - ROLE_APP_ADMIN_PRESCRIPTOR_LIST
        - ROLE_APP_ADMIN_PRESCRIPTOR_VIEW
        - ROLE_APP_ADMIN_PRESCRIPTOR_CREATE
        - ROLE_APP_ADMIN_PRESCRIPTOR_EDIT
        - ROLE_APP_ADMIN_PRESCRIPTOR_DELETE
        - ROLE_APP_ADMIN_CAMPANYA_LIST
        - ROLE_APP_ADMIN_CAMPANYA_VIEW
        - ROLE_APP_ADMIN_CAMPANYA_CREATE
        - ROLE_APP_ADMIN_CAMPANYA_EDIT
        - ROLE_APP_ADMIN_CAMPANYA_DELETE
        - ROLE_APP_ADMIN_CATEGORIA_LIST
        - ROLE_APP_ADMIN_CATEGORIA_VIEW
        - ROLE_APP_ADMIN_CATEGORIA_CREATE
        - ROLE_APP_ADMIN_CATEGORIA_EDIT
        - ROLE_APP_ADMIN_CATEGORIA_DELETE
        - ROLE_APP_ADMIN_CATEGORIA_LIST
        - ROLE_APP_ADMIN_COMERCIAL_VIEW
        - ROLE_APP_ADMIN_COMERCIAL_CREATE
        - ROLE_APP_ADMIN_COMERCIAL_EDIT
        - ROLE_APP_ADMIN_COMERCIAL_DELETE
        - ROLE_APP_ADMIN_COMERCIAL_LIST
        - ROLE_APP_ADMIN_CAMPANYA_SERIAL_LIST
        - ROLE_APP_ADMIN_CAMPANYA_SERIAL_VIEW
        - ROLE_APP_ADMIN_CAMPANYA_SERIAL_CREATE
        - ROLE_APP_ADMIN_CAMPANYA_SERIAL_EDIT
        - ROLE_APP_ADMIN_CAMPANYA_SERIAL_DELETE
        - ROLE_APP_ADMIN_MARKETING_VIEW
        - ROLE_APP_ADMIN_MARKETING_CREATE
        - ROLE_APP_ADMIN_MARKETING_EDIT
        - ROLE_APP_ADMIN_MARKETING_DELETE
        - ROLE_APP_ADMIN_MARKETING_LIST
        ROLE_ADMIN_RIESGOS_CCF:
        - ROLE_APP_ADMIN_ALERTAS_INFORMA_LIST
        - ROLE_APP_ADMIN_ALERTAS_INFORMA_VIEW
        - ROLE_APP_ADMIN_ALERTAS_INFORMA_CREATE
        - ROLE_APP_ADMIN_ALERTAS_INFORMA_EDIT
        ROLE_AREA_COMERCIAL:
        - ROLE_APP_ADMIN_AREA_COMERCIAL_LIST
        - ROLE_APP_ADMIN_AREA_COMERCIAL_VIEW
        - ROLE_APP_ADMIN_AREA_COMERCIAL_CREATE
        - ROLE_APP_ADMIN_AREA_COMERCIAL_EDIT
        ROLE_AREA_COMERCIAL_RESPONSABLE:
        - ROLE_APP_ADMIN_AREA_COMERCIAL_LIST
        - ROLE_APP_ADMIN_AREA_COMERCIAL_VIEW
        - ROLE_APP_ADMIN_AREA_COMERCIAL_CREATE
        - ROLE_APP_ADMIN_AREA_COMERCIAL_EDIT
        - ROLE_APP_ADMIN_AREA_COMERCIAL_MANAGE_PRIORITARIAS
        ROLE_AREA_RIESGOS:
        - ROLE_APP_ADMIN_AREA_RIESGOS_LIST
        - ROLE_APP_ADMIN_AREA_RIESGOS_VIEW
        - ROLE_APP_ADMIN_AREA_RIESGOS_CREATE
        - ROLE_APP_ADMIN_AREA_RIESGOS_EDIT
        ROLE_SISTEMAS_CEF_ADMIN:
        - ROLE_ADMIN_ADMIN_LIST
        - ROLE_ADMIN_ADMIN_VIEW
        - ROLE_ADMIN_ADMIN_CREATE
        - ROLE_ADMIN_ADMIN_EDIT
        - ROLE_ADMIN_USER_DELETE
        ROLE_SISTEMAS_CEF_USER:
        - ROLE_ADMIN_USER_LIST
        - ROLE_ADMIN_USER_VIEW
        - ROLE_ADMIN_USER_CREATE
        - ROLE_ADMIN_USER_EDIT
        - ROLE_ADMIN_USER_DELETE
        ROLE_SISTEMAS_CEF_COMPANY:
        - ROLE_ADMIN_COMPANY_LIST
        - ROLE_ADMIN_COMPANY_VIEW
        - ROLE_ADMIN_COMPANY_CREATE
        - ROLE_ADMIN_COMPANY_EDIT
        - ROLE_ADMIN_COMPANY_DELETE
        ROLE_SISTEMAS_CEF_ROLE:
        - ROLE_ADMIN_ROLE_LIST
        - ROLE_ADMIN_ROLE_VIEW
        - ROLE_ADMIN_ROLE_CREATE
        - ROLE_ADMIN_ROLE_EDIT
        - ROLE_ADMIN_ROLE_DELETE
        ROLE_SISTEMAS_CEF_WIDGET:
        - ROLE_ADMIN_WIDGET_LIST
        - ROLE_ADMIN_WIDGET_VIEW
        - ROLE_ADMIN_WIDGET_CREATE
        - ROLE_ADMIN_WIDGET_EDIT
        - ROLE_ADMIN_WIDGET_DELETE
        ROLE_ADMIN_UPLOAD_FILES:
        - ROLE_ADMIN_UPLOADS_LIST
        - ROLE_ADMIN_TRANSLATIONS_LIST
        ROLE_SISTEMAS_CEF_COMMERCIALOFFICE:
        - ROLE_ADMIN_COMMERCIALOFFICE_LIST
        - ROLE_ADMIN_COMMERCIALOFFICE_VIEW
        - ROLE_ADMIN_COMMERCIALOFFICE_CREATE
        - ROLE_ADMIN_COMMERCIALOFFICE_EDIT
        - ROLE_ADMIN_COMMERCIALOFFICE_DELETE
        ROLE_SISTEMAS_CEF_COMMERCIALRESPONSABLE:
        - ROLE_ADMIN_COMMERCIALRESPONSABLE_LIST
        - ROLE_ADMIN_COMMERCIALRESPONSABLE_VIEW
        - ROLE_ADMIN_COMMERCIALRESPONSABLE_CREATE
        - ROLE_ADMIN_COMMERCIALRESPONSABLE_EDIT
        - ROLE_ADMIN_COMMERCIALRESPONSABLE_DELETE
        ROLE_SISTEMAS_CEF_GESTORRESPONSABLE:
        - ROLE_ADMIN_GESTORRESPONSABLE_LIST
        - ROLE_ADMIN_GESTORRESPONSABLE_VIEW
        - ROLE_ADMIN_GESTORRESPONSABLE_CREATE
        - ROLE_ADMIN_GESTORRESPONSABLE_EDIT
        - ROLE_ADMIN_GESTORRESPONSABLE_DELETE
        ROLE_SISTEMAS_CEF_GESTORHORIZONTAL:
        - ROLE_ADMIN_GESTORHORIZONTAL_LIST
        - ROLE_ADMIN_GESTORHORIZONTAL_VIEW
        - ROLE_ADMIN_GESTORHORIZONTAL_CREATE
        - ROLE_ADMIN_GESTORHORIZONTAL_EDIT
        - ROLE_ADMIN_GESTORHORIZONTAL_DELETE
        ROLE_SISTEMAS_CEF_ALERTAS:
        - ROLE_ADMIN_COMERCIALALERTAS_LIST
        - ROLE_ADMIN_COMERCIALALERTAS_VIEW
        - ROLE_ADMIN_COMERCIALALERTAS_CREATE
        - ROLE_ADMIN_COMERCIALALERTAS_EDIT
        - ROLE_ADMIN_COMERCIALALERTAS_DELETE
        ROLE_SISTEMAS_COMERCIALTASKS:
        - ROLE_ADMIN_COMERCIALTASKS_LIST
        - ROLE_ADMIN_COMERCIALTASKS_VIEW
        - ROLE_ADMIN_COMERCIALTASKS_CREATE
        - ROLE_ADMIN_COMERCIALTASKS_EDIT
        - ROLE_ADMIN_COMERCIALTASKS_DELETE
        - ROLE_ADMIN_COMERCIALTASKTYPES_LIST
        - ROLE_ADMIN_COMERCIALTASKTYPES_VIEW
        - ROLE_ADMIN_COMERCIALTASKTYPES_CREATE
        - ROLE_ADMIN_COMERCIALTASKTYPES_EDIT
        - ROLE_ADMIN_COMERCIALTASKTYPES_DELETE
        - ROLE_ADMIN_COMERCIALTASKSTATUS_LIST
        - ROLE_ADMIN_COMERCIALTASKSTATUS_VIEW
        - ROLE_ADMIN_COMERCIALTASKSTATUS_CREATE
        - ROLE_ADMIN_COMERCIALTASKSTATUS_EDIT
        - ROLE_ADMIN_COMERCIALTASKSTATUS_DELETE
        ROLE_SISTEMAS_CEF_MURO:
        - ROLE_ADMIN_COMERCIALMUROTIPO_LIST
        - ROLE_ADMIN_COMERCIALMUROTIPO_VIEW
        - ROLE_ADMIN_COMERCIALMUROTIPO_CREATE
        - ROLE_ADMIN_COMERCIALMUROTIPO_EDIT
        - ROLE_ADMIN_COMERCIALMUROTIPO_DELETE
        - ROLE_ADMIN_COMERCIALMURO_LIST
        - ROLE_ADMIN_COMERCIALMURO_VIEW
        - ROLE_ADMIN_COMERCIALMURO_CREATE
        - ROLE_ADMIN_COMERCIALMURO_EDIT
        - ROLE_ADMIN_COMERCIALMURO_DELETE
        ROLE_SISTEMAS_EXPEDIENTES:
        - ROLE_ADMIN_COMERCIALEXPEDIENTES_LIST
        - ROLE_ADMIN_COMERCIALEXPEDIENTES_EDIT
        - ROLE_ADMIN_COMERCIALEXPEDIENTESCOTIZACIONES_LIST
        - ROLE_ADMIN_COMERCIALEXPEDIENTESCOTIZACIONES_EDIT
        ROLE_SISTEMAS_VISIT:
        - ROLE_ADMIN_VISIT_LIST
        - ROLE_ADMIN_VISIT_EDIT
        - ROLE_ADMIN_VISIT_VIEW
        - ROLE_ADMIN_VISIT_CREATE
        - ROLE_ADMIN_VISIT_DELETE

        ROLE_RIESGOS_CCF:   [ROLE_USER, ROLE_ADMIN_RIESGOS_CCF]
        ROLE_USER_VIAJES:   [ROLE_USER]
        ROLE_PUBLI_CCF:     [ROLE_USER, ROLE_ADMIN_PUBLI_CCF]
        ROLE_SISTEMAS_CEF:  [ROLE_SISTEMAS_CEF_DOCUMENTACION, ROLE_SISTEMAS_CEF_TIPO_EMPRESA, ROLE_SISTEMAS_CEF_SEGURO_TIPO, ROLE_SISTEMAS_CEF_SEGURO_AMBITO, ROLE_SISTEMAS_CEF_SEGURO_TRANSPORTE, ROLE_SISTEMAS_CEF_SEGURO_FRANQUICIA, ROLE_SISTEMAS_CEF_SEGURO_TARIFA, ROLE_USER_VIAJES, ROLE_SISTEMAS_CEF_USER, ROLE_SISTEMAS_CEF_COMPANY, ROLE_SISTEMAS_CEF_ROLE, ROLE_SISTEMAS_CEF_WIDGET, ROLE_SISTEMAS_CEF_COMMERCIALOFFICE, ROLE_SISTEMAS_CEF_COMMERCIALRESPONSABLE, ROLE_SISTEMAS_CEF_GESTORRESPONSABLE, ROLE_SISTEMAS_CEF_GESTORHORIZONTAL, ROLE_SISTEMAS_CEF_MURO]
        ROLE_ADMIN_GUEST:   [ROLE_SISTEMAS_VISIT, ROLE_SISTEMAS_EXPEDIENTES, ROLE_SISTEMAS_CEF_MURO, ROLE_SISTEMAS_COMERCIALTASKS, ROLE_SISTEMAS_CEF_ALERTAS, ROLE_USER, ROLE_USER_VIAJES, ROLE_SONATA_ADMIN, ROLE_SISTEMAS_CEF, ROLE_PUBLI_CCF, ROLE_RIESGOS_CCF, ROLE_BASICO_GDS, ROLE_AREA_COMERCIAL, ROLE_AREA_RIESGOS, ROLE_AREA_COMERCIAL_RESPONSABLE]
        ROLE_ADMIN:         [ROLE_ADMIN_GUEST, ROLE_SISTEMAS_CEF_ADMIN, ROLE_ADMIN_UPLOAD_FILES]
        ROLE_SUPER_ADMIN:   [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
