#CONF DESTINATION SERVER
USER="root"
PASSWORD=""
PORT="3306"
SERVER="localhost"
DB="smart"

#CONF ORIGIN SERVER
USER_ORIGIN="root"
PASSWORD_ORIGIN=""
PORT_ORIGIN="3306"
SERVER_ORIGIN="localhost"
DB_ORIGIN="smart_origin"

#CONF LOCAL SERVER
USER_LOCAL="root"
PASSWORD_LOCAL=""
PORT_LOCAL="3306"
SERVER_LOCAL="localhost"
DB_LOCAL="smart"
DB_LOCAL_ORIGIN="smart_origin"

UPLOAD_ORIGIN="C:/uploadsOrigin"
UPLOAD_DESTINATION="C:/uploads"
