SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE role;
ALTER TABLE role AUTO_INCREMENT = 1;
TRUNCATE comercial_expediente_perdido_motivo;
ALTER TABLE comercial_expediente_perdido_motivo AUTO_INCREMENT = 1;
TRUNCATE comercial_expediente_status;
ALTER TABLE comercial_expediente_status AUTO_INCREMENT = 1;
TRUNCATE comercial_producto;
ALTER TABLE comercial_producto AUTO_INCREMENT = 1;
TRUNCATE tipo_canal;
ALTER TABLE tipo_canal AUTO_INCREMENT = 1;
TRUNCATE user;
ALTER TABLE user AUTO_INCREMENT = 1;
TRUNCATE vertical;
ALTER TABLE vertical AUTO_INCREMENT = 1;
TRUNCATE company;
ALTER TABLE company AUTO_INCREMENT = 1;
TRUNCATE dashboard_widgets;
ALTER TABLE dashboard_widgets AUTO_INCREMENT = 1;
TRUNCATE charge;
ALTER TABLE charge AUTO_INCREMENT = 1;
TRUNCATE reason;
ALTER TABLE reason AUTO_INCREMENT = 1;
TRUNCATE status;
ALTER TABLE status AUTO_INCREMENT = 1;
TRUNCATE visit;
ALTER TABLE visit AUTO_INCREMENT = 1;
TRUNCATE document_type;
ALTER TABLE document_type AUTO_INCREMENT = 1;
TRUNCATE admin;
ALTER TABLE admin AUTO_INCREMENT = 1;
TRUNCATE comercial_task_type;
ALTER TABLE comercial_task_type AUTO_INCREMENT = 1;
TRUNCATE comercial_task_status;
ALTER TABLE comercial_task_status AUTO_INCREMENT = 1;
TRUNCATE comercial_task;
ALTER TABLE comercial_task AUTO_INCREMENT = 1;
TRUNCATE comercial_muro;
ALTER TABLE comercial_muro AUTO_INCREMENT = 1;
TRUNCATE comercial_expediente;
ALTER TABLE comercial_expediente AUTO_INCREMENT = 1;
TRUNCATE comercial_expediente_favoritos;
ALTER TABLE comercial_expediente_favoritos AUTO_INCREMENT = 1;
TRUNCATE comercial_cotizacion;
ALTER TABLE comercial_cotizacion AUTO_INCREMENT = 1;
TRUNCATE comercial_expediente_cotizaciones;
ALTER TABLE comercial_expediente_cotizaciones AUTO_INCREMENT = 1;
TRUNCATE comercial_cotizacion_favoritos;
ALTER TABLE comercial_cotizacion_favoritos AUTO_INCREMENT = 1;
TRUNCATE comercial_alertas;
ALTER TABLE comercial_alertas AUTO_INCREMENT = 1;
TRUNCATE document;
ALTER TABLE document AUTO_INCREMENT = 1;
TRUNCATE comercial_muro_estados;
ALTER TABLE  comercial_muro_estados AUTO_INCREMENT = 1;
TRUNCATE comercial_muro_adjuntos;
ALTER TABLE  comercial_muro_adjuntos AUTO_INCREMENT = 1;
TRUNCATE contact;
ALTER TABLE  contact AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
